ALTER TABLE users
  MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT FIRST,
  MODIFY COLUMN name VARCHAR(191) NULL AFTER id,
  MODIFY COLUMN email VARCHAR(191) NOT NULL AFTER name,
  MODIFY COLUMN password VARCHAR(191) NOT NULL AFTER email,
  MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER password,
  MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER createdAt;
